# action.yaml
name: 'Uptick CI Slack Shamer'
description: 'A Github Action that sends a slack message on error and praises the user when it has been fixed'
inputs:
  command:
    description: 'To shame or to praise'
    required: true
    default: "shame"
  SLACK_TOKEN:
    description: 'Slack api token'
    required: true
  SLACK_CHANNEl:
    description: 'Slack channel to post to'
    required: true
  GITHUB_TOKEN:
    description: 'Github api token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'