on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: uptick/actions-shame@v1.5.0
        with:
          command: 'shame'
          SLACK_TOKEN: ''
          SLACK_CHANNEL: ''
          GITHUB_TOKEN: ''